.babelrc
index.html
package.json
server.js
src/App.js
src/api/User.js
src/assets/_button.scss
src/assets/_field.scss
src/assets/_form.scss
src/assets/_login.scss
src/assets/style.scss
src/components/BoxForm.js
src/components/FieldButton.js
src/components/FieldInput.js
src/main.js
src/pages/Login.js
src/store/modules/index.js
src/store/modules/user.js
webpack.config.js
yarn.lock

This is PR is about this issue #1

Add page of login

---

src/App.js
src/api/User.js
src/pages/Signup.js

This pull request add the new page of signup, and add the Hashrouter, and links in Log In page

Add the new page of Sign Up

---

src/App.js
src/components/PrivateRouter.js
src/pages/Dashboard.js
src/pages/Login.js
src/utils/checkAuth.js

This PR is for keep dashboard page safe to unlogged users, but when that use do the login its redirect to dashboard page.

Add the PrivateRouter component and initial page of dashboard

---

package.json
src/components/TableTransactions.js
tests/components/TableTransactions.test.js
yarn.lock

Add filter by month

---

src/assets/_table-transactions.scss
src/components/TableTransactionList.js
src/components/TableTransactions.js
tests/components/TableTransactionList.test.js
tests/components/TableTransactions.test.js
tests/components/__snapshots__/TableTransactionList.test.js.snap
tests/components/__snapshots__/TableTransactions.test.js.snap

Add transactions loading

---

package-lock.json
package.json
src/main.tsx
src/pages/Login.tsx
src/services/auth.ts

Add html and css of login page

---

livechangelog.md
src/hooks/useUser.js
src/main.tsx

Add test Add token on apollo client and create useUser

---

src/components/Text.tsx
src/theme.ts

Text component

---

src/components/Header.tsx
src/components/Text.tsx
src/theme.ts

feature header

---

package.json
src/components/Button.tsx
src/components/ButtonIcon.tsx
src/theme.ts
yarn.lock

Feacture Button-Icon

---

src/components/Checkbox.tsx
src/theme.ts

Feature Check Box

---

src/components/Textarea.tsx
src/theme.ts

Feature Textarea component

---

src/components/Checkbox.tsx
src/components/Radio.tsx
src/theme.ts

Feature button-radio

---

src/components/SwitchButton.tsx
src/theme.ts

Feature switch button

---

src/components/Select.tsx

Feature select

---

src/pages/ChangePassword/index.tsx
src/pages/Login/index.tsx
src/pages/ResetPassword/index.tsx
src/pages/SignUp/index.tsx
src/schema/auth.ts

fix button loading and bug of form

---

src/pages/Dashboard/SideBar/Information.tsx
src/pages/Transactions/Operation/FooterContainer.tsx
src/utils/calcOperations.ts

improvement add operations data to content footer

---

src/components/Container.tsx
src/graphql/AuthGql.ts
src/pages/SignUp/index.tsx
src/schema/auth.ts

Add the currency field on register page

---

src/graphql/Operations.ts
src/hooks/useAccountFilters.tsx
src/hooks/useAccounts.tsx
src/hooks/useCategories.tsx
src/hooks/useOperations.tsx
src/models/index.ts
src/pages/Dashboard/Accounts/index.tsx
src/pages/Dashboard/NavBar/AccountSelector.tsx
src/pages/Dashboard/Operations/Operation/CategorySelect.tsx
src/pages/Dashboard/Operations/Operation/OperationItem.tsx
src/pages/Dashboard/Operations/index.tsx
src/pages/Dashboard/SideBar/Info.tsx
src/pages/Dashboard/SideBar/Information.tsx
src/theme.ts

Use the currency field on account to change the InputCurrency

---

src/components/LoadingData.tsx
src/components/Pagination.tsx
src/constants/Transactions.tsx
src/graphql/Categories.ts
src/hooks/useCategories.tsx
src/main.tsx
src/models/index.ts
src/pages/Dashboard/Accounts/AddAccount/index.tsx
src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
src/pages/Dashboard/Categories/AddCategory/index.tsx
src/pages/Dashboard/Categories/UpdateCategory/index.tsx
src/pages/Dashboard/Categories/index.tsx
src/pages/Dashboard/Categories/styles.tsx
src/pages/Dashboard/NavBar/Menu.tsx
src/pages/Dashboard/NavBar/style/Menu.style.tsx
src/pages/Dashboard/Operations/Operation/CategorySelect.tsx
src/pages/Dashboard/index.tsx
src/schema/checkField.ts

Feature list, create, delete and update categories

---

src/graphql/Operations.ts

fix: add accountId on filter on balance

Release v2.2.1

---

src/pages/Dashboard/Operations/Operation/FooterContainer.tsx

fix: add the previous balance to the footer

Release v2.4.1
